### PR TITLE
Fixes an issue with resolv.conf on Ubuntu

### PR DESCRIPTION
**Pull request by jterry75**
Resolves: #171

### CODE REVIEW

**Comment by jterry75** [comment]
Let me build and run this once before merge but I think this does the trick.

**Comment by jterry75** [comment]
Verified.

**Comment by clarity99** [comment]
I'm running into this sam problem now in November 2018 :
λ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     true

Running in experimental mode with LCOW containers

**Comment by jhowardmsft** [comment]
@clarity99 Right. I doubt this fix was backported to 18.06.

**Pull request merged**
