### PR TITLE
(Manual)Vendor opencontainers/runtime-spec

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Did a manual copy as vendoring still not setup correctly in this repo. Commit is 29686dbc5559d93fb1ef402eeda3e35c38d75af4 where CommandLine has been added. (Yes, not strictly relevant for opengcs, but for consistency).

@jterry75 PTAL

### CODE REVIEW

**Comment by jterry75** [comment]
We dont need this but LGTM

**Comment by jhowardmsft** [comment]
Yeah, know it's not needed, just getting consistency across the board from all associated repos.

**Comment by jterry75** [comment]
Since its a manual vendor did you check all files in specs-go? this LGTM

**Comment by jhowardmsft** [comment]
Yes, I did

**Pull request merged**
