### PR TITLE
Formally deprecate LCOW v1

### PR DESCRIPTION
**Pull request by jterry75**
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by jterry75** [comment]
@katiewasnothere - Once this is in I will send the removal PR

**Comment by jterry75** [comment]
@kevpar - PTAL as well

**Comment by lowenna** [comment]
Nice 😁

**Comment by jterry75** [comment]
@lowenna - Dude miss you

**Pull request merged**
