### PR TITLE
Updated patches with previsouly missing Signed-off-by line

### PR DESCRIPTION
**Pull request by soccerGB**
For the following two files:
patch_9pfs_vsock-transport.patch
patch_lower-the-minimum-PMEM-size.patch

### CODE REVIEW

**Comment by gupta-ak** [comment]
Shouldn't the commit hash change once your sign it?

**Comment by dcui** [comment]
I have fixed the hv_sock related commit hash with Cheng-mean in another PR, but I'm not sure if Chean-mean needs to update any hash related to his own files, if any.

**Comment by gupta-ak** [comment]
The top of the patches have a hash:
```
From cbce811777331869e4b2ef3b5cc04de0dc9a0d05 Mon Sep 17 00:00:00 2001
From: Cheng-mean Liu <soccerl@microsoft.com>
```

I think that's the commit hash, so I think these two patches need to be updated with the correct hash. Like this:
```
git commit -s --amend ...
git format-patch ...
```

**Comment by dcui** [comment]
So it looks @soccerGB needs to make a further fix.
Let' wait his reply.

**Pull request closed without merging**
