### PR TITLE
Add a retry when connecting stdin/stdout/stderr

### PR DESCRIPTION
**Pull request by gupta-ak**
Temp fix until underlying vsock issue is solved.

### CODE REVIEW

**Comment by jterry75** [comment]
I think you need to add this when calling Dial for the p9fs mapped directories too

**Comment by gupta-ak** [comment]
Are you talking about this: https://github.com/Microsoft/opengcs/blob/ab442e9a042246e5e6c87102ed56faa6d3925458/service/gcs/core/gcs/storage.go#L265

despite the name, i think it's a transport object:
https://github.com/Microsoft/opengcs/blob/ab442e9a042246e5e6c87102ed56faa6d3925458/service/gcs/core/gcs/gcs.go#L36

**Comment by jterry75** [comment]
`transport.Transport` is the interface. If you look in main.go you see that its initialized with a `VsockTransport{}` so it could have the same issue on `Dial`.

**Comment by gupta-ak** [comment]
isn't that what I just changed?
`func (t *VsockTransport) Dial(port uint32) (Connection, error) { `

Is there another implementation of the Dial interface that I'm missing?

**Comment by gupta-ak** [comment]
oh it also turns out that the virtsock library masked the ETIMEDOUT, so now I just retry on any error.

**Pull request merged**
