### PR TITLE
Refactor the v2 runtime into its own packages

### PR DESCRIPTION
**Pull request by jterry75**
This is the non-scary part of the change. So sending out so we can make the other part easier to review.

1. Moves all v2 storage code to the appropriate internal/storage packages and adds unit tests for them.
2. Moves all v2 networking calls to the appropriate internal/networking pacakge
3. Moves the v2 HCS runtime to an internal/runtime/hcsv2 package
4. Moves the v2 devicemapper package (unused currently) to the internal/storage package.
5. Updates all v2 code to be LF
6. Removes the devices.HostDevices we copied from runc now that our updated vendor of runc includes this.
7. Splits the uvm.go into Host/Container/Process files to make the changes easier to understand for eash section.

### CODE REVIEW

**Comment by jterry75** [comment]
@jhowardmsft - I have verified all this with the shim tests. There are no "new" regressions from moving all this code out.

**Comment by jterry75** [comment]
@jhowardmsft - Wit the latest 2d6f for the SCSI retry I see no issues on cri-stress

**Comment by jhowardmsft** [comment]
It's caused a v1 regression. From vmcompute analytic starting a service VM. 

```
onecore\vm\compute\common\bridge\bridgecomputeservice.cpp(72)\vmcompute.exe!00007FF72292385B: (caller: 00007FF7229247DB) LogHr(91) tid(218c) 80004005 Unspecified error
    Msg:[Client Error [failed to mount layers for container 1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm: upperdirPath: "/tmp/0/scratch/upper", and workdirPath: "/tmp/0/scratch/work" must be emty when readonly==true] gcs:overlay.go:Mount:57] CallContext:[\HcsRpc_StartSystem\ComputeSystemManager_Start\LinuxContainer_Start\BridgeComputeService_CreateComputeSystem] 
```

JSON document to VMCompute:
```
"HCS ComputeSystem Document" cid=1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm json="{\"SystemType\":\"container\",\"Name\":\"1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm\",\"Layers\":null,\"HvPartition\":true,\"HvRuntime\":{\"ImagePath\":\"C:\\\\Program Files\\\\Linux Containers\",\"LinuxInitrdFile\":\"initrd.img\",\"LinuxKernelFile\":\"kernel\"},\"ContainerType\":\"linux\",\"TerminateOnLastHandleClosed\":true}"
time="2019-04-11T09:20:24.564060600-07:00" level=debug msg="hcsshim::CreateComputeSystem - End Operation - Success" cid=1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm
time="2019-04-11T09:20:24.564060600-07:00" level=debug msg="opengcs: StartUtilityVM: uvm created, starting..."
time="2019-04-11T09:20:24.565095300-07:00" level=debug msg="hcsshim::ComputeSystem::Start - Begin Operation" cid=1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm
time="2019-04-11T09:20:24.722645000-07:00" level=error msg="hcsshim::ComputeSystem::Start - End Operation - Error" cid=1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm error="Start 1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm: Unspecified error"
time="2019-04-11T09:20:24.730003100-07:00" level=debug msg="opengcs: StartUtilityVM: uvm failed to start: container 1774f10ee9b5d8560a6120ef6fa0f8ba4124ea5421265525ffe5362db643cd91_svm encountered an error during Start: failure in a Windows system call: Unspecified error (0x80004005)"
```

**Comment by jterry75** [comment]
@jhowardmsft - 385d fixes this error. It turns out v1 has been incorrectly creating a lower/work dir even when no scratch is present.

**Pull request merged**
