### PR TITLE
Sinankaya/unittests

### PR DESCRIPTION
**Pull request by franksinankaya**

### CODE REVIEW

**Comment by franksinankaya** [comment]
Thanks. Done.

**Comment by jterry75** [comment]
LGTM assuming the CI passes.

**Comment by franksinankaya** [comment]
"runtime/runc/runc_test.go:400:32: undefined: Contains". I'm not a go expert but it worked for me when I tested locally. Any ideas?

**Comment by jterry75** [comment]
For Ginkgo I think you want `ContainSubstring` for an Expect query

**Pull request merged**
