### PR TITLE
Remove the v1 gcs

### PR DESCRIPTION
**Pull request by jterry75**
LCOW is only supported RS5+ which already had LCOW v2. We no longer need to
keep the v1 gcs impl.

Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by jterry75** [comment]
**DO NOT MERGE** - Need to verify tests

**Comment by katiewasnothere** [comment]
@jterry75 do you have an update on this? Is there anything we can take over?

**Comment by katiewasnothere** [comment]
Closing this in favor of https://github.com/microsoft/opengcs/pull/390

**Comment by jterry75** [comment]
@katiewasnothere - Thanks! I'm totally cool with removing it just wasnt a top pri. Please do!

**Pull request closed without merging**
